=== esden/stm32cube-database/db/mcu/bootpath/BWD.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2012 (x64) (http://www.altova.com) by USER USER (STMICROELECTRONICS) -->
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="BootpathWizardDescription">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BootPathList">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="BootPathDescription" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="InternalName" type="xs:string"/>
										<xs:element name="ShortDescription" type="xs:string"/>
										<xs:element name="LongDescription" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="Condition" type="xs:string" use="optional"/>
														<xs:attribute name="Type" type="xs:string" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="SecurePreemptedIPList" type="xs:string" minOccurs="0"/>
										<xs:element name="Semaphore" type="xs:string" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="Type" type="xs:string" use="required"/>
									<xs:attribute name="Secure" type="xs:boolean" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="WizardTitleList">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="WizardTitle">
								<xs:complexType>
									<xs:attribute name="Condition" type="xs:string" use="optional"/>
									<xs:attribute name="Title" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="WizardChoiceGroup"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="WizardChoiceGroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Title" type="xs:string"/>
				<xs:element ref="WizardChoice" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="WizardChoice">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BootPath" type="xs:string"/>
				<xs:element ref="WizardChoiceGroup" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="Condition" type="xs:string" use="optional"/>
			<xs:attribute name="Diagnostic" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== esden/stm32cube-database/db/mcu/bootpath/tzen1/Bootpath_STM32H57x.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<BootpathWizardDescription xsi:noNamespaceSchemaLocation="../BWD.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <BootPathList>
        <BootPathDescription Type="Application" Secure="true">
            <InternalName>LEGACY</InternalName>
            <ShortDescription>Secure Application</ShortDescription>
            <LongDescription Type="png" Condition="S_PRO_STRUCT_DUAL">BootPath/DualNonSecureSecure/D-S-NS-step1.png</LongDescription>
			<LongDescription Type="png" Condition="S_PRO_STRUCT_SINGLE_SECURE">BootPath/OnlySecure/Appli-S-OS-step1.png</LongDescription>
			<LongDescription Type="png">BootPath/BootPath.png</LongDescription>
        </BootPathDescription>

        <BootPathDescription Type="Application" Secure="true">
            <InternalName>OEM_IROT</InternalName>
            <ShortDescription>Secure Application</ShortDescription>
            <LongDescription Type="png" Condition="S_PRO_STRUCT_DUAL">BootPath/DualNonSecureSecure/OEM-iRoT-Appli-D-S-NS-step2.png</LongDescription>
			<LongDescription Type="png" Condition="S_PRO_STRUCT_SINGLE_SECURE">BootPath/OnlySecure/OEM-iRoT-Appli-S-OS-step2.png</LongDescription>
        </BootPathDescription>

        <BootPathDescription Type="Ongoing">
            <InternalName>OEM_IROT_ONGOING</InternalName>
            <ShortDescription>OEM immutable Root of Trust (OEM-iRoT)</ShortDescription>
            <LongDescription Type="png" Condition="S_PRO_STRUCT_DUAL">BootPath/DualNonSecureSecure/OEM-iRoT-Appli-D-S-NS-step1.png</LongDescription>
			<LongDescription Type="png" Condition="S_PRO_STRUCT_SINGLE_SECURE">BootPath/OnlySecure/OEM-iRoT-Appli-S-OS-step1.png</LongDescription>
        </BootPathDescription>

        <BootPathDescription Type="Ongoing">
            <InternalName>OEM_IROT_UROT_ONGOING</InternalName>
            <ShortDescription>updatable Root of Trust (uRoT)</ShortDescription>
			<LongDescription Type="png" Condition="S_PRO_STRUCT_DUAL">BootPath/DualNonSecureSecure/OEM-iRoT-uRoT-Appli-D-S-NS-step2.png</LongDescription>
            <LongDescription Type="png" Condition="S_PRO_STRUCT_SINGLE_SECURE">BootPath/OnlySecure/OEM-iRoT-uRoT-Appli-S-OS-step2.png</LongDescription>
        </BootPathDescription>

        <BootPathDescription Type="Application" Secure="true">
            <InternalName>OEM_IROT_UROT</InternalName>
            <ShortDescription>Secure Application</ShortDescription>
			<LongDescription Type="png" Condition="S_PRO_STRUCT_DUAL">BootPath/DualNonSecureSecure/OEM-iRoT-uRoT-Appli-D-S-NS-step3.png</LongDescription>			
            <LongDescription Type="png" Condition="S_PRO_STRUCT_SINGLE_SECURE">BootPath/OnlySecure/OEM-iRoT-uRoT-Appli-S-OS-step3.png</LongDescription>
        </BootPathDescription>


        <BootPathDescription Type="Application" Secure="true">
            <InternalName>ST_IROT</InternalName>
            <ShortDescription>Secure Application</ShortDescription>
            <LongDescription Type="png" Condition="S_PRO_STRUCT_DUAL">BootPath/DualNonSecureSecure/ST-iRoT-Appli-D-S-NS-step2.png</LongDescription>
			<LongDescription Type="png" Condition="S_PRO_STRUCT_SINGLE_SECURE">BootPath/OnlySecure/ST-iRoT-Appli-S-OS-step2.png</LongDescription>
        </BootPathDescription>

        <BootPathDescription Type="Ongoing">
            <InternalName>ST_IROT_ONGOING</InternalName>
            <ShortDescription>ST immutable Root of Trust (ST-iRoT)</ShortDescription>
            <LongDescription Type="png" Condition="S_PRO_STRUCT_DUAL">BootPath/DualNonSecureSecure/ST-iRoT-uRoT-Appli-D-S-NS-step1.png</LongDescription>
			<LongDescription Type="png" Condition="S_PRO_STRUCT_SINGLE_SECURE">BootPath/OnlySecure/ST-iRoT-Appli-S-OS-step1.png</LongDescription>
			<LongDescription Type="png">BootPath/NonSecure/ST-iRoT-Appli-NS-step1.png</LongDescription>			
        </BootPathDescription>

        <BootPathDescription Type="Ongoing">
            <InternalName>ST_IROT_UROT_ONGOING</InternalName>
            <ShortDescription>updatable Root of Trust (uRoT)</ShortDescription>
            <LongDescription Type="png" Condition="S_PRO_STRUCT_DUAL">BootPath/DualNonSecureSecure/ST-iRoT-uRoT-Appli-D-S-NS-step2.png</LongDescription>
			<LongDescription Type="png" Condition="S_PRO_STRUCT_SINGLE_SECURE">BootPath/OnlySecure/ST-iRoT-uRoT-Appli-S-OS-step2.png</LongDescription>
			<LongDescription Type="png">BootPath/NonSecure/ST-iRoT-uRoT-Appli-NS-step2.png</LongDescription>			
        </BootPathDescription>

        <BootPathDescription Type="Application" Secure="true">
            <InternalName>ST_IROT_UROT</InternalName>
            <ShortDescription>Secure Application</ShortDescription>
            <LongDescription Type="png" Condition="S_PRO_STRUCT_DUAL">BootPath/DualNonSecureSecure/ST-iRoT-uRoT-Appli-D-S-NS-step3.png</LongDescription>
			<LongDescription Type="png" Condition="S_PRO_STRUCT_SINGLE_SECURE">BootPath/OnlySecure/ST-iRoT-uRoT-Appli-S-OS-step3.png</LongDescription>
        </BootPathDescription>

        <BootPathDescription Type="Ongoing">
            <InternalName>ST_IROT_UROT_SECURE_MANAGER_ONOING</InternalName>
            <ShortDescription>Secure Manager</ShortDescription>
			<LongDescription Type="png">BootPath/ToBeDefined.png</LongDescription>
        </BootPathDescription>

        <BootPathDescription Type="Application" Secure="true">
            <InternalName>ST_IROT_UROT_SECURE_MANAGER_SECURE</InternalName>
            <ShortDescription>Secure Application</ShortDescription>
			<LongDescription Type="png">BootPath/ToBeDefined.png</LongDescription>
        </BootPathDescription>

        <BootPathDescription Type="Application" Secure="false">
            <InternalName>ST_IROT_UROT_SECURE_MANAGER</InternalName>
            <ShortDescription>Secure Manager Non Secure Application</ShortDescription>
			<LongDescription Type="png">BootPath/NonSecure/ST-iRoT-uRoT-SecureManager-Appli-NS-step3.png</LongDescription>
			<SecurePreemptedIPList>AES,OTFDEC1,RNG,PKA,HASH,SAES</SecurePreemptedIPList>
			<Semaphore>S_BOOTPATH_SMGR</Semaphore>
        </BootPathDescription>

    </BootPathList>

    <WizardTitleList>
        <WizardTitle Title="TZEN=1 'Dual Non Secure / Secure' project" Condition="S_PRO_STRUCT_DUAL" />
        <WizardTitle Title="TZEN=1 'Only Secure' project" Condition="S_PRO_STRUCT_SINGLE_SECURE" />
        <WizardTitle Title="TZEN=1 'Only Non Secure' project" />
    </WizardTitleList>
		
    <WizardChoiceGroup>
        <Title>Boot Step#1</Title>
        <WizardChoice Condition="S_PRO_STRUCT_DUAL | S_PRO_STRUCT_SINGLE_SECURE" Diagnostic="Not available with Non Secure Only Project" >
            <BootPath>LEGACY</BootPath>
        </WizardChoice>

        <WizardChoice  Condition="S_PRO_STRUCT_DUAL | S_PRO_STRUCT_SINGLE_SECURE" Diagnostic="Not available with Non Secure Only Project" >
            <BootPath>OEM_IROT_ONGOING</BootPath>

            <WizardChoiceGroup>
                <Title>Boot Step#2</Title>
                <WizardChoice>
                    <BootPath>OEM_IROT</BootPath>
                </WizardChoice>

                <WizardChoice>
                    <BootPath>OEM_IROT_UROT_ONGOING</BootPath>

                    <WizardChoiceGroup>
                        <Title>Boot Step#3</Title>
                        <WizardChoice>
                            <BootPath>OEM_IROT_UROT</BootPath>
                        </WizardChoice>
                    </WizardChoiceGroup>

                </WizardChoice>

            </WizardChoiceGroup>

        </WizardChoice>
		
        <WizardChoice>
            <BootPath>ST_IROT_ONGOING</BootPath>
            <WizardChoiceGroup>
                <Title>Boot Step#2</Title>

                <WizardChoice Condition="S_PRO_STRUCT_DUAL | S_PRO_STRUCT_SINGLE_SECURE" Diagnostic="Not available with Non Secure Only Project" >
                    <BootPath>ST_IROT</BootPath>
                </WizardChoice>

                <WizardChoice>
                    <BootPath>ST_IROT_UROT_ONGOING</BootPath>

                    <WizardChoiceGroup>
                        <Title>Boot Step#3</Title>

                        <WizardChoice Condition="S_PRO_STRUCT_DUAL | S_PRO_STRUCT_SINGLE_SECURE" Diagnostic="Not available with Non Secure Only Project" >
                            <BootPath>ST_IROT_UROT</BootPath>
                        </WizardChoice>

                        <WizardChoice Condition="!(S_PRO_STRUCT_DUAL | S_PRO_STRUCT_SINGLE_SECURE)" Diagnostic="Available for Non Secure Only Project" >
							<BootPath>ST_IROT_UROT_SECURE_MANAGER</BootPath>
                        </WizardChoice>
                    </WizardChoiceGroup>

                </WizardChoice>

            </WizardChoiceGroup>
        </WizardChoice>

    </WizardChoiceGroup>
</BootpathWizardDescription>
